var texte = document.querySelector(".Texte");
var Exper = document.querySelector("#Exper");
var Diplo = document.querySelector("#Diplo");
var Compt = document.querySelector("#Compt");
var Cent = document.querySelector("#Cent");
var texte1;
var texte2;
var texte3;



Exper.addEventListener("mouseover", function(){ texte1 = "<span class='red'> <br/>&nbsp;Fév. / Mars 2018</span> <br/>&nbsp; <span class='gras'>Assistante du Directeur Artistique - Label Agence - Paris(75) -<br/>&nbsp; Stage</span> <br/><br/>&nbsp; - Elaboration et coordination à la conception d'une application <br/>&nbsp; - Conception d'une carte de visite <br/>&nbsp; - Réalisation de mock-ups et d'une maquette pour une &nbsp;&nbsp;&nbsp;&nbsp;application <br/>&nbsp; - Création de contenus pour un site internet <br/>&nbsp; - Réalisation d'une charte graphique <br/>&nbsp; - Retouche d'images <span class='red center'> <br/><br/><br/>&nbsp;Oct. 2015 / Nov. 2017</span> <br/>&nbsp;&nbsp;<span class='gras'>Assistante de Communication - Centre Culturel Paul B. - <br/>&nbsp; Massy(91) - CDD</span> <br/><br/>&nbsp; - Conception d'affiches, flyers pour l'impression et visuels pour <br/>&nbsp;&nbsp;&nbsp;&nbsp;le web <br/>&nbsp; - Gestion, coordination et suivi des campagnes d'affichage";
texte2= "<br/>&nbsp; - Mise à jour du site internet et du fichier des contacts presse <br/>&nbsp; - Veille sur internet concernant l'actualité des artistes de la <br/>&nbsp;&nbsp;&nbsp;&nbsp;programmation <br/>&nbsp; - Mise à jour de la revue de presse <br/>&nbsp; - Distribution des supports de communication <br/>&nbsp; - Organisation logistique d'un événement (Arbre de Noel pour <br/>&nbsp;&nbsp;&nbsp;&nbsp;l'entreprise Danone) <br/>&nbsp; - Accueil des spectateurs et billeterie <br/>&nbsp; - Accueil des classes pour les séances scolaires <br/><br/><br/><span class='red'>&nbsp;Juin 2013 / Oct. 2015 </span><br/>&nbsp; <span class='gras'>Équipière Polyvalente – Mc Donald’s – Massy (91) – CDI</span> <br/><br/>&nbsp; - Accueil de la clientèle <br/>&nbsp; - Prise de commande <br/>&nbsp; - Préparation des plateaux";
texte3= "<span class='red'> <br/><br/><br/>&nbsp;Déc. 2012 / Mars 2013</span><br/><br/>&nbsp; <span class='gras'>Vendeuse – Kloé – Antony (92) – CDD</span> <br/><br/>&nbsp; - Vente et conseil <br/>&nbsp; - Réception des colis <br/>&nbsp; - Mise en place des rayons <span class='red'> <br/><br/><br/>&nbsp;Juil. 2012</span> <br/>&nbsp; <span class='gras'>Chargée d’accueil – Société Générale (91) – CDD</span> <br/><br/>&nbsp; - Accueillir <br/>&nbsp; - Informer <br/>&nbsp; - Classer <span class='red'><br/><br/><br/>&nbsp;Déc. 2011 / Janv. 2012</span> <br/>&nbsp; <span class='gras'>Vendeuse - Kloé – Antony (92) – Stage</span>  <br/><br/>&nbsp; - Vente et conseil <br/>&nbsp; - Réception des colis <br/>&nbsp; - Mise en place des rayons <br/><br/>";
texte.innerHTML= texte1 + texte2 + texte3;});
/**/

Diplo.addEventListener("mouseover", function(){ texte.innerHTML = "<br/><br/><span class='red'> &nbsp;2018</span> &nbsp; <span class='gras'>Développeur Web</span> • Simplon.co – Paris (75) <span class='red'> <br/><br/>&nbsp;2016</span> &nbsp; <span class='gras'>Photoshop, les fondamentaux</span> • Agecif – Paris (75) <span class='red'><br/><br/>&nbsp;2013</span> &nbsp;  <span class='gras'>1ère année BTS Communication</span> • ITIC à Paris (75) <br/><br/><span class='red'>&nbsp;2012</span> &nbsp; <span class='gras'>BAC Professionnel Commerce</span> • Lycée Saint Eugène de &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Palaiseau (91)";});
Compt.addEventListener("mouseover", function(){ texte.innerHTML = "<br/><br/><span class='red'> &nbsp; Anglais </span> : Oral et écrit niveau scolaire <br/><br/><span class='red'> &nbsp; Espagnol</span> :    Oral et écrit niveau scolaire <br/><br/><span class='red'> &nbsp; Informatiques</span> : HTML , CSS , JAVA , Sketch , Marvel , Photoshop , &nbsp;&nbsp;&nbsp;InDesign , Logiciel de billetterie (Aparté) , B2I , PACK OFFICE <br/>&nbsp;&nbsp;&nbsp;(Word , Excel , PowerPoint)";});
Cent.addEventListener("mouseover", function(){ texte.innerHTML = "<br/><br/>&nbsp;<span class='red'>•</span> Musiques africaines <br/><br/>&nbsp;<span class='red'>•</span> Concert <br/><br/>&nbsp;<span class='red'>•</span> Cinéma  <br/><br/>&nbsp;<span class='red'>•</span> Organisation d’un vide-greniers et d’une course pour enfants au &nbsp;&nbsp;&nbsp;sein d’une association à Massy Graviers";});
